# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run
before_script:
  - cd client/app
  - npm install

pages:
  script:
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - /public
