
stages:
  - build
  - deploy


build-client:
  stage: build
  image: node:lts-bullseye
  script:
    - cd client/app
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - client/app/build

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  dependencies:
    - build-client
  needs:
    - build-client
  script:
    - mv client/app/build/ public
  artifacts:
    paths:
      - public
