image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - client/app/node_modules/

before_script:
  - cd client/app
  - npm install

build-client:
  stage: build
  variables:
    PUBLIC_URL: https://gitlab.com/mad-foley/portfolio
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - client/app/build

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-client
  needs:
    - build-client
  script:
    - mv client/app/build/ public
  artifacts:
    paths:
      - public
