version: "3"

services:
  client:
    container_name: portfolio-client
    image: node:latest
    command: /bin/bash run.sh
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./client/app:/app
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
